aws:
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:http://localhost:8000}
    region: ${AWS_DYNAMODB_REGION:eu-central-1}
    access-key: ${AWS_ACCESS_KEY_ID:dummy}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:dummy}
    table-name: ${AWS_DYNAMODB_TABLE_NAME:payment-history}
spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all

      properties:
        enable.idempotence: true